#!/usr/bin/env bash
# Build Novex.app from the Swift Package and install to ~/Applications.
# Ad-hoc signs so TCC permissions (Full Disk Access, Automation, etc.) survive rebuilds.

set -euo pipefail

cd "$(dirname "$0")/.."

APP_NAME="Novex"
BUNDLE_ID="com.tarun.novex"
VERSION="0.1.0"
INSTALL_DIR="${HOME}/Applications"
APP_DIR="${INSTALL_DIR}/${APP_NAME}.app"
CONTENTS_DIR="${APP_DIR}/Contents"
MACOS_DIR="${CONTENTS_DIR}/MacOS"

echo "==> swift build -c release --product Novex"
# Build ONLY the app product. Building the whole package in release would also
# try to compile NovexDevTests, whose `@testable import NovexCore` only works in
# a testing-enabled (debug) build and fails under -c release.
swift build -c release --product Novex

echo "==> packaging ${APP_DIR}"
mkdir -p "${INSTALL_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${MACOS_DIR}"
cp ".build/release/${APP_NAME}" "${MACOS_DIR}/${APP_NAME}"
chmod +x "${MACOS_DIR}/${APP_NAME}"

# App icon (generated by Scripts/make-icon.sh). Optional — skip if absent.
if [ -f "Resources/AppIcon.icns" ]; then
    mkdir -p "${CONTENTS_DIR}/Resources"
    cp "Resources/AppIcon.icns" "${CONTENTS_DIR}/Resources/AppIcon.icns"
    echo "==> bundled app icon"
else
    echo "==> no Resources/AppIcon.icns (run Scripts/make-icon.sh to generate one)"
fi

cat > "${CONTENTS_DIR}/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <!--
      WORKAROUND for a Swift-runtime crash: SwiftUI Button actions go through
      MainActor.assumeIsolated → swift_task_isCurrentExecutor, which on recent
      Swift CRASHES (EXC_BAD_ACCESS) instead of returning false when it can't
      confirm the main executor. Our UI is hosted via NSHostingController inside
      a manually-managed NSWindow, so that executor check is unreliable and every
      button tap could segfault. This env var restores the legacy non-crashing
      behavior. LSEnvironment applies to LaunchServices launches (open / Finder /
      login item). See Swift runtime: SWIFT_IS_CURRENT_EXECUTOR_LEGACY_MODE_OVERRIDE.
    -->
    <key>LSEnvironment</key>
    <dict>
        <key>SWIFT_IS_CURRENT_EXECUTOR_LEGACY_MODE_OVERRIDE</key>
        <string>legacy</string>
    </dict>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${VERSION}</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMicrophoneUsageDescription</key>
    <string>Novex uses the microphone to let you ask questions about your mail by voice.</string>
    <key>NSSpeechRecognitionUsageDescription</key>
    <string>Novex transcribes your spoken questions on-device using Apple's Speech framework. Nothing is uploaded.</string>
    <key>NSCalendarsFullAccessUsageDescription</key>
    <string>Novex reads your calendar on your Mac to show what's next and connect meetings to the related emails. Your calendar never leaves your computer.</string>
    <key>NSRemindersFullAccessUsageDescription</key>
    <string>Novex reads your Reminders on your Mac so it can show what's on your plate alongside your mail. Your reminders never leave your computer.</string>
</dict>
</plist>
EOF

# Signing strategy (zero-cost / no paid Developer ID):
#
# Prefer a STABLE self-signed code-signing identity ("Novex Local"). macOS keys
# TCC permissions (Full Disk Access, Microphone) to the signing identity, so a
# stable cert makes those grants PERSIST across rebuilds. Ad-hoc signing
# (`--sign -`) re-hashes on every build → macOS silently revokes Full Disk
# Access each time, which masquerades as "mail stopped syncing."
#
# One-time setup (no cost): Keychain Access → Certificate Assistant →
#   Create a Certificate…  Name: "Novex Local",  Identity Type: Self Signed Root,
#   Certificate Type: Code Signing → Create.  Every rebuild then reuses it.
SIGN_IDENTITY="Novex Local"
# NOTE: no -v here. A self-signed "Novex Local" cert is untrusted
# (CSSMERR_TP_NOT_TRUSTED), so `find-identity -v` (valid-only) hides it — but
# codesign signs with it fine, and TCC keys on the (stable) signing identity, not
# on system trust, so Full Disk Access still persists across rebuilds.
if security find-identity -p codesigning 2>/dev/null | grep -q "${SIGN_IDENTITY}"; then
    echo "==> signing with stable identity: ${SIGN_IDENTITY} (TCC grants persist across rebuilds)"
    codesign --force --deep --sign "${SIGN_IDENTITY}" "${APP_DIR}"
else
    echo "==> ad-hoc signing (no '${SIGN_IDENTITY}' identity found)"
    echo "    NOTE: ad-hoc re-hashes every build → macOS revokes Full Disk Access each rebuild."
    echo "    To make FDA persist, create a self-signed 'Novex Local' Code Signing cert in Keychain Access."
    codesign --force --deep --sign - "${APP_DIR}"
fi

echo ""
echo "Built: ${APP_DIR}"

LABEL="com.tarun.novex"
if launchctl print "gui/$(id -u)/${LABEL}" >/dev/null 2>&1; then
    pkill -f Novex 2>/dev/null || true
    sleep 0.4
    launchctl kickstart -k "gui/$(id -u)/${LABEL}" >/dev/null 2>&1 || true
    echo "Restarted via launchd (login item is installed)."
else
    echo ""
    echo "Login item not installed yet. To install:"
    echo "  Scripts/install-login-item.sh"
    echo ""
    echo "Or launch once manually:"
    echo "  open '${APP_DIR}'"
fi
